# Generated by Django 5.2.4 on 2025-08-19 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistido',
            fields=[
                ('id_assist', models.AutoField(primary_key=True, serialize=False)),
                ('nmcompleto_assist', models.CharField(max_length=255)),
                ('numero_assist', models.CharField(blank=True, max_length=50, null=True)),
                ('dn_assist', models.DateField()),
                ('nmgenitor_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('nmgenitora_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('nmresponsavel_assist', models.CharField(choices=[('tio', 'Tio'), ('tia', 'Tia'), ('avo', 'Avô/Avó'), ('primo', 'Primo/Prima'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('outro_responsavel', models.CharField(blank=True, help_text="Preencher se o tipo do responsável for 'Outro'.", max_length=255, null=True)),
                ('escola_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('rua_assist', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro_assist', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade_assist', models.CharField(blank=True, max_length=100, null=True)),
                ('numerocasa_assist', models.CharField(blank=True, max_length=20, null=True)),
                ('nm_conselheiro', models.CharField(blank=True, max_length=255, null=True)),
                ('gestante_assist', models.BooleanField(default=False)),
                ('arquivomorto_assist', models.BooleanField(default=False)),
                ('filaarquivomorto_assist', models.BooleanField(default=False)),
                ('dtarquivomorto_assist', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irmaos',
            fields=[
                ('id_irmaos', models.AutoField(primary_key=True, serialize=False)),
                ('id_assist_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irmao1', to='assistido.assistido')),
                ('id_assist_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irmao2', to='assistido.assistido')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id_telefone', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('obs_telefone', models.TextField(blank=True, null=True)),
                ('id_assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='assistido.assistido')),
            ],
        ),
    ]
