# Generated by Django 5.1.5 on 2025-08-19 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistido',
            name='DTCADASTRO',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
    ]
