# Generated by Django 5.2.4 on 2025-08-20 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0002_assistido_dtcadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizador',
            fields=[
                ('id_local', models.AutoField(primary_key=True, serialize=False)),
                ('dt_local', models.DateField(verbose_name='Data do Localizador')),
                ('destino_local', models.CharField(max_length=255, verbose_name='Destino do Localizador')),
                ('id_assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizadores', to='assistido.assistido')),
            ],
        ),
    ]
