# Generated by Django 5.1.5 on 2025-08-25 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0003_localizador'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistido',
            name='nm_conselheiro',
        ),
        migrations.AddField(
            model_name='assistido',
            name='arquivado_assist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistido',
            name='id_conselheiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistidos', to='usuario.conselheiro'),
        ),
    ]
