# Generated by Django 5.1.5 on 2025-10-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0004_remove_assistido_nm_conselheiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistido',
            name='id_conselheiro',
        ),
    ]
