# Generated by Django 5.1.5 on 2025-10-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0005_remove_assistido_id_conselheiro'),
        ('usuario', '0002_conselheira_secretaria_delete_conselheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistido',
            name='id_conselheira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistidos', to='usuario.conselheira'),
        ),
    ]
