# Generated by Django 5.1.5 on 2025-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistido', '0006_assistido_id_conselheira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistido',
            name='dn_assist',
            field=models.DateField(blank=True, null=True),
        ),
    ]
