# Generated by Django 5.1.5 on 2025-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conselheiro',
            fields=[
                ('id_conselheiro', models.AutoField(primary_key=True, serialize=False)),
                ('nm_conselheiro', models.CharField(max_length=255)),
            ],
        ),
    ]
